<a href="https://colab.research.google.com/github/sojeonglim/sojeonglim.github.io/blob/master/%EC%8B%A4%EC%8A%B5_Simple_ETL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
%load_ext sql

ID와 PW와 (본인스키마)를 자신의 것으로 변경

In [3]:
%sql postgresql://sojeong_lim:Sojeong_Lim!1@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev

'Connected: sojeong_lim@dev'

In [4]:
%%sql

DROP TABLE IF EXISTS sojeong_lim.name_gender;
CREATE TABLE sojeong_lim.name_gender (
   name varchar(32),
   gender varchar(8)
);

 * postgresql://sojeong_lim:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
Done.
Done.

[]

In [5]:
import psycopg2

# Redshift connection 함수
# 본인 ID/PW 사용!
def get_Redshift_connection():
    host = "learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com"
    redshift_user = "sojeong_lim"
    redshift_pass = "Sojeong_Lim!1"
    port = 5439
    dbname = "dev"
    conn = psycopg2.connect("dbname={dbname} user={user} host={host} password={password} port={port}".format(
        dbname=dbname,
        user=redshift_user,
        password=redshift_pass,
        host=host,
        port=port
    ))
    conn.set_session(autocommit=True)
    return conn.cursor()

# ETL 함수를 하나씩 정의

In [6]:
import requests

def extract(url):
    f = requests.get(url)
    return (f.text)

In [7]:
def transform(text):
    lines = text.split("\n")
    return lines

In [8]:
def load(lines):
    # BEGIN과 END를 사용해서 SQL 결과를 트랜잭션으로 만들어주는 것이 좋음
    # BEGIN;DELETE FROM (본인의스키마).name_gender;INSERT INTO TABLE VALUES ('KEEYONG', 'MALE');....;END;
    cur = get_Redshift_connection()
    for r in lines:
        if r != '':
            (name, gender) = r.split(",")
            print(name, "-", gender)
            sql = "INSERT INTO sojeong_lim.name_gender VALUES ('{n}', '{g}')".format(n=name, g=gender)
            print(sql)
            cur.execute(sql)

In [9]:
%%sql
SELECT * FROM sojeong_lim.name_gender limit 10;

 * postgresql://sojeong_lim:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
0 rows affected.

[]

# 이제 Extract부터 함수를 하나씩 실행

In [ ]:
link = "https://s3-geospatial.s3-us-west-2.amazonaws.com/name_gender.csv"

data = extract(link)

In [ ]:
data

'name,gender\nAdaleigh,F\nAmryn,Unisex\nApurva,Unisex\nAryion,M\nAlixia,F\nAlyssarose,F\nArvell,M\nAibel,M\nAtiyyah,F\nAdlie,F\nAnyely,F\nAamoni,F\nAhman,M\nArlane,F\nArmoney,F\nAtzhiry,F\nAntonette,F\nAkeelah,F\nAbdikadir,M\nArinze,M\nArshaun,M\nAlexandro,M\nAyriauna,F\nAqib,M\nAlleya,F\nAavah,F\nAnesti,Unisex\nAdalaide,F\nAnalena,F\nAlaeyah,F\nAlbena,F\nAimi,F\nAdwaith,M\nArkady,M\nAstyn,Unisex\nAdelee,F\nAgata,F\nAlegna,F\nAltan,M\nAhnaleigh,F\nAlgie,Unisex\nAshanti,F\nAislyn,F\nAdaleine,F\nAnthnoy,M\nAlgernon,M\nAeryona,F\nAdrinne,F\nAddell,F\nAvril,F\nAhni,F\nAimon,M\nAdolpho,M\nAhuva,F\nAurielle,F\nAveana,F\nAliyia,F\nAlesander,M\nAdnrea,F\nAnjae,F\nAlvine,F\nAdorah,F\nAdlemi,F\nAlesi,F\nAlontae,M\nAntonny,M\nAdarah,F\nAyreanna,F\nAntyon,M\nAndia,F\nAshla,F\nAspyn,F\nAntwanett,F\nAundreia,F\nAudella,F\nAmari,Unisex\nArsha,Unisex\nAricella,F\nAdan,M\nApasra,F\nAlaysha,F\nAnderson,M\nAurelius,M\nAerial,F\nAverleigh,F\nAslean,F\nArniesha,F\nAsyana,F\nAnnjane,F\nAmabella,F\nAustinjohn,M\nArloween,F\nAlula,M\nAnemone,F\nAmorina,F\nAnureet,F\nArric,M\nAntonne,M\nAlyre,M\nAnnaise,F\n'

In [ ]:
lines = transform(data)

In [ ]:
lines

['name,gender',
 'Adaleigh,F',
 'Amryn,Unisex',
 'Apurva,Unisex',
 'Aryion,M',
 'Alixia,F',
 'Alyssarose,F',
 'Arvell,M',
 'Aibel,M',
 'Atiyyah,F',
 'Adlie,F',
 'Anyely,F',
 'Aamoni,F',
 'Ahman,M',
 'Arlane,F',
 'Armoney,F',
 'Atzhiry,F',
 'Antonette,F',
 'Akeelah,F',
 'Abdikadir,M',
 'Arinze,M',
 'Arshaun,M',
 'Alexandro,M',
 'Ayriauna,F',
 'Aqib,M',
 'Alleya,F',
 'Aavah,F',
 'Anesti,Unisex',
 'Adalaide,F',
 'Analena,F',
 'Alaeyah,F',
 'Albena,F',
 'Aimi,F',
 'Adwaith,M',
 'Arkady,M',
 'Astyn,Unisex',
 'Adelee,F',
 'Agata,F',
 'Alegna,F',
 'Altan,M',
 'Ahnaleigh,F',
 'Algie,Unisex',
 'Ashanti,F',
 'Aislyn,F',
 'Adaleine,F',
 'Anthnoy,M',
 'Algernon,M',
 'Aeryona,F',
 'Adrinne,F',
 'Addell,F',
 'Avril,F',
 'Ahni,F',
 'Aimon,M',
 'Adolpho,M',
 'Ahuva,F',
 'Aurielle,F',
 'Aveana,F',
 'Aliyia,F',
 'Alesander,M',
 'Adnrea,F',
 'Anjae,F',
 'Alvine,F',
 'Adorah,F',
 'Adlemi,F',
 'Alesi,F',
 'Alontae,M',
 'Antonny,M',
 'Adarah,F',
 'Ayreanna,F',
 'Antyon,M',
 'Andia,F',
 'Ashla,F',
 'Aspyn,F',
 'Antwanett,F',
 'Aundreia,F',
 'Audella,F',
 'Amari,Unisex',
 'Arsha,Unisex',
 'Aricella,F',
 'Adan,M',
 'Apasra,F',
 'Alaysha,F',
 'Anderson,M',
 'Aurelius,M',
 'Aerial,F',
 'Averleigh,F',
 'Aslean,F',
 'Arniesha,F',
 'Asyana,F',
 'Annjane,F',
 'Amabella,F',
 'Austinjohn,M',
 'Arloween,F',
 'Alula,M',
 'Anemone,F',
 'Amorina,F',
 'Anureet,F',
 'Arric,M',
 'Antonne,M',
 'Alyre,M',
 'Annaise,F',
 '']

In [ ]:
load(lines)

name - gender
INSERT INTO keeyong.name_gender VALUES ('name', 'gender')
Adaleigh - F
INSERT INTO keeyong.name_gender VALUES ('Adaleigh', 'F')
Amryn - Unisex
INSERT INTO keeyong.name_gender VALUES ('Amryn', 'Unisex')
Apurva - Unisex
INSERT INTO keeyong.name_gender VALUES ('Apurva', 'Unisex')
Aryion - M
INSERT INTO keeyong.name_gender VALUES ('Aryion', 'M')
Alixia - F
INSERT INTO keeyong.name_gender VALUES ('Alixia', 'F')
Alyssarose - F
INSERT INTO keeyong.name_gender VALUES ('Alyssarose', 'F')
Arvell - M
INSERT INTO keeyong.name_gender VALUES ('Arvell', 'M')
Aibel - M
INSERT INTO keeyong.name_gender VALUES ('Aibel', 'M')
Atiyyah - F
INSERT INTO keeyong.name_gender VALUES ('Atiyyah', 'F')
Adlie - F
INSERT INTO keeyong.name_gender VALUES ('Adlie', 'F')
Anyely - F
INSERT INTO keeyong.name_gender VALUES ('Anyely', 'F')
Aamoni - F
INSERT INTO keeyong.name_gender VALUES ('Aamoni', 'F')
Ahman - M
INSERT INTO keeyong.name_gender VALUES ('Ahman', 'M')
Arlane - F
INSERT INTO keeyong.name_gender VALUES ('Arlane', 'F')
Armoney - F
INSERT INTO keeyong.name_gender VALUES ('Armoney', 'F')
Atzhiry - F
INSERT INTO keeyong.name_gender VALUES ('Atzhiry', 'F')
Antonette - F
INSERT INTO keeyong.name_gender VALUES ('Antonette', 'F')
Akeelah - F
INSERT INTO keeyong.name_gender VALUES ('Akeelah', 'F')
Abdikadir - M
INSERT INTO keeyong.name_gender VALUES ('Abdikadir', 'M')
Arinze - M
INSERT INTO keeyong.name_gender VALUES ('Arinze', 'M')
Arshaun - M
INSERT INTO keeyong.name_gender VALUES ('Arshaun', 'M')
Alexandro - M
INSERT INTO keeyong.name_gender VALUES ('Alexandro', 'M')
Ayriauna - F
INSERT INTO keeyong.name_gender VALUES ('Ayriauna', 'F')
Aqib - M
INSERT INTO keeyong.name_gender VALUES ('Aqib', 'M')
Alleya - F
INSERT INTO keeyong.name_gender VALUES ('Alleya', 'F')
Aavah - F
INSERT INTO keeyong.name_gender VALUES ('Aavah', 'F')
Anesti - Unisex
INSERT INTO keeyong.name_gender VALUES ('Anesti', 'Unisex')
Adalaide - F
INSERT INTO keeyong.name_gender VALUES ('Adalaide', 'F')
Analena - F
INSERT INTO keeyong.name_gender VALUES ('Analena', 'F')
Alaeyah - F
INSERT INTO keeyong.name_gender VALUES ('Alaeyah', 'F')
Albena - F
INSERT INTO keeyong.name_gender VALUES ('Albena', 'F')
Aimi - F
INSERT INTO keeyong.name_gender VALUES ('Aimi', 'F')
Adwaith - M
INSERT INTO keeyong.name_gender VALUES ('Adwaith', 'M')
Arkady - M
INSERT INTO keeyong.name_gender VALUES ('Arkady', 'M')
Astyn - Unisex
INSERT INTO keeyong.name_gender VALUES ('Astyn', 'Unisex')
Adelee - F
INSERT INTO keeyong.name_gender VALUES ('Adelee', 'F')
Agata - F
INSERT INTO keeyong.name_gender VALUES ('Agata', 'F')
Alegna - F
INSERT INTO keeyong.name_gender VALUES ('Alegna', 'F')
Altan - M
INSERT INTO keeyong.name_gender VALUES ('Altan', 'M')
Ahnaleigh - F
INSERT INTO keeyong.name_gender VALUES ('Ahnaleigh', 'F')
Algie - Unisex
INSERT INTO keeyong.name_gender VALUES ('Algie', 'Unisex')
Ashanti - F
INSERT INTO keeyong.name_gender VALUES ('Ashanti', 'F')
Aislyn - F
INSERT INTO keeyong.name_gender VALUES ('Aislyn', 'F')
Adaleine - F
INSERT INTO keeyong.name_gender VALUES ('Adaleine', 'F')
Anthnoy - M
INSERT INTO keeyong.name_gender VALUES ('Anthnoy', 'M')
Algernon - M
INSERT INTO keeyong.name_gender VALUES ('Algernon', 'M')
Aeryona - F
INSERT INTO keeyong.name_gender VALUES ('Aeryona', 'F')
Adrinne - F
INSERT INTO keeyong.name_gender VALUES ('Adrinne', 'F')
Addell - F
INSERT INTO keeyong.name_gender VALUES ('Addell', 'F')
Avril - F
INSERT INTO keeyong.name_gender VALUES ('Avril', 'F')
Ahni - F
INSERT INTO keeyong.name_gender VALUES ('Ahni', 'F')
Aimon - M
INSERT INTO keeyong.name_gender VALUES ('Aimon', 'M')
Adolpho - M
INSERT INTO keeyong.name_gender VALUES ('Adolpho', 'M')
Ahuva - F
INSERT INTO keeyong.name_gender VALUES ('Ahuva', 'F')
Aurielle - F
INSERT INTO keeyong.name_gender VALUES ('Aurielle', 'F')
Aveana - F
INSERT INTO keeyong.name_gender VALUES ('Aveana', 'F')
Aliyia - F
INSERT INTO keeyong.name_gender VALUES ('Aliyia', 'F')
Alesander - M
INSERT INTO keeyong.name_gender VALUES ('Alesander', 'M')
Adnrea - F
INSERT INTO keeyong.name_gender VALUES ('Adnrea', 'F')
Anjae - F
INSERT INTO keeyong.name_gender VALUES ('Anjae', 'F')
Alvine - F
INSERT INTO keeyong.name_gender VALUES ('Alvine', 'F')
Adorah - F
INSERT INTO keeyong.name_gender VALUES ('Adorah', 'F')
Adlemi - F
INSERT INTO keeyong.name_gender VALUES ('Adlemi', 'F')
Alesi - F
INSERT INTO keeyong.name_gender VALUES ('Alesi', 'F')
Alontae - M
INSERT INTO keeyong.name_gender VALUES ('Alontae', 'M')
Antonny - M
INSERT INTO keeyong.name_gender VALUES ('Antonny', 'M')
Adarah - F
INSERT INTO keeyong.name_gender VALUES ('Adarah', 'F')
Ayreanna - F
INSERT INTO keeyong.name_gender VALUES ('Ayreanna', 'F')
Antyon - M
INSERT INTO keeyong.name_gender VALUES ('Antyon', 'M')
Andia - F
INSERT INTO keeyong.name_gender VALUES ('Andia', 'F')
Ashla - F
INSERT INTO keeyong.name_gender VALUES ('Ashla', 'F')
Aspyn - F
INSERT INTO keeyong.name_gender VALUES ('Aspyn', 'F')
Antwanett - F
INSERT INTO keeyong.name_gender VALUES ('Antwanett', 'F')
Aundreia - F
INSERT INTO keeyong.name_gender VALUES ('Aundreia', 'F')
Audella - F
INSERT INTO keeyong.name_gender VALUES ('Audella', 'F')
Amari - Unisex
INSERT INTO keeyong.name_gender VALUES ('Amari', 'Unisex')
Arsha - Unisex
INSERT INTO keeyong.name_gender VALUES ('Arsha', 'Unisex')
Aricella - F
INSERT INTO keeyong.name_gender VALUES ('Aricella', 'F')
Adan - M
INSERT INTO keeyong.name_gender VALUES ('Adan', 'M')
Apasra - F
INSERT INTO keeyong.name_gender VALUES ('Apasra', 'F')
Alaysha - F
INSERT INTO keeyong.name_gender VALUES ('Alaysha', 'F')
Anderson - M
INSERT INTO keeyong.name_gender VALUES ('Anderson', 'M')
Aurelius - M
INSERT INTO keeyong.name_gender VALUES ('Aurelius', 'M')
Aerial - F
INSERT INTO keeyong.name_gender VALUES ('Aerial', 'F')
Averleigh - F
INSERT INTO keeyong.name_gender VALUES ('Averleigh', 'F')
Aslean - F
INSERT INTO keeyong.name_gender VALUES ('Aslean', 'F')
Arniesha - F
INSERT INTO keeyong.name_gender VALUES ('Arniesha', 'F')
Asyana - F
INSERT INTO keeyong.name_gender VALUES ('Asyana', 'F')
Annjane - F
INSERT INTO keeyong.name_gender VALUES ('Annjane', 'F')
Amabella - F
INSERT INTO keeyong.name_gender VALUES ('Amabella', 'F')
Austinjohn - M
INSERT INTO keeyong.name_gender VALUES ('Austinjohn', 'M')
Arloween - F
INSERT INTO keeyong.name_gender VALUES ('Arloween', 'F')
Alula - M
INSERT INTO keeyong.name_gender VALUES ('Alula', 'M')
Anemone - F
INSERT INTO keeyong.name_gender VALUES ('Anemone', 'F')
Amorina - F
INSERT INTO keeyong.name_gender VALUES ('Amorina', 'F')
Anureet - F
INSERT INTO keeyong.name_gender VALUES ('Anureet', 'F')
Arric - M
INSERT INTO keeyong.name_gender VALUES ('Arric', 'M')
Antonne - M
INSERT INTO keeyong.name_gender VALUES ('Antonne', 'M')
Alyre - M
INSERT INTO keeyong.name_gender VALUES ('Alyre', 'M')
Annaise - F
INSERT INTO keeyong.name_gender VALUES ('Annaise', 'F')

In [ ]:
%%sql

SELECT COUNT(1)
FROM keeyong.name_gender;

 * postgresql://keeyong:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
1 rows affected.

[(202,)]

In [ ]:
%%sql

SELECT *
FROM keeyong.name_gender;

 * postgresql://keeyong:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
202 rows affected.

[('name', 'gender'),
 ('Adaleigh', 'F'),
 ('Amryn', 'Unisex'),
 ('Apurva', 'Unisex'),
 ('Aryion', 'M'),
 ('Alixia', 'F'),
 ('Alyssarose', 'F'),
 ('Arvell', 'M'),
 ('Aibel', 'M'),
 ('Atiyyah', 'F'),
 ('Adlie', 'F'),
 ('Anyely', 'F'),
 ('Aamoni', 'F'),
 ('Ahman', 'M'),
 ('Arlane', 'F'),
 ('Armoney', 'F'),
 ('Atzhiry', 'F'),
 ('Antonette', 'F'),
 ('Akeelah', 'F'),
 ('Abdikadir', 'M'),
 ('Arinze', 'M'),
 ('Arshaun', 'M'),
 ('Alexandro', 'M'),
 ('Ayriauna', 'F'),
 ('Aqib', 'M'),
 ('Alleya', 'F'),
 ('Aavah', 'F'),
 ('Anesti', 'Unisex'),
 ('Adalaide', 'F'),
 ('Analena', 'F'),
 ('Alaeyah', 'F'),
 ('Albena', 'F'),
 ('Aimi', 'F'),
 ('Adwaith', 'M'),
 ('Arkady', 'M'),
 ('Astyn', 'Unisex'),
 ('Adelee', 'F'),
 ('Agata', 'F'),
 ('Alegna', 'F'),
 ('Altan', 'M'),
 ('Ahnaleigh', 'F'),
 ('Algie', 'Unisex'),
 ('Ashanti', 'F'),
 ('Aislyn', 'F'),
 ('Adaleine', 'F'),
 ('Anthnoy', 'M'),
 ('Algernon', 'M'),
 ('Aeryona', 'F'),
 ('Adrinne', 'F'),
 ('Addell', 'F'),
 ('Avril', 'F'),
 ('Ahni', 'F'),
 ('Aimon', 'M'),
 ('Adolpho', 'M'),
 ('Ahuva', 'F'),
 ('Aurielle', 'F'),
 ('Aveana', 'F'),
 ('Aliyia', 'F'),
 ('Alesander', 'M'),
 ('Adnrea', 'F'),
 ('Anjae', 'F'),
 ('Alvine', 'F'),
 ('Adorah', 'F'),
 ('Adlemi', 'F'),
 ('Alesi', 'F'),
 ('Alontae', 'M'),
 ('Antonny', 'M'),
 ('Adarah', 'F'),
 ('Ayreanna', 'F'),
 ('Antyon', 'M'),
 ('Andia', 'F'),
 ('Ashla', 'F'),
 ('Aspyn', 'F'),
 ('Antwanett', 'F'),
 ('Aundreia', 'F'),
 ('Audella', 'F'),
 ('Amari', 'Unisex'),
 ('Arsha', 'Unisex'),
 ('Aricella', 'F'),
 ('Adan', 'M'),
 ('Apasra', 'F'),
 ('Alaysha', 'F'),
 ('Anderson', 'M'),
 ('Aurelius', 'M'),
 ('Aerial', 'F'),
 ('Averleigh', 'F'),
 ('Aslean', 'F'),
 ('Arniesha', 'F'),
 ('Asyana', 'F'),
 ('Annjane', 'F'),
 ('Amabella', 'F'),
 ('Austinjohn', 'M'),
 ('Arloween', 'F'),
 ('Alula', 'M'),
 ('Anemone', 'F'),
 ('Amorina', 'F'),
 ('Anureet', 'F'),
 ('Arric', 'M'),
 ('Antonne', 'M'),
 ('Alyre', 'M'),
 ('Annaise', 'F'),
 ('name', 'gender'),
 ('Adaleigh', 'F'),
 ('Amryn', 'Unisex'),
 ('Apurva', 'Unisex'),
 ('Aryion', 'M'),
 ('Alixia', 'F'),
 ('Alyssarose', 'F'),
 ('Arvell', 'M'),
 ('Aibel', 'M'),
 ('Atiyyah', 'F'),
 ('Adlie', 'F'),
 ('Anyely', 'F'),
 ('Aamoni', 'F'),
 ('Ahman', 'M'),
 ('Arlane', 'F'),
 ('Armoney', 'F'),
 ('Atzhiry', 'F'),
 ('Antonette', 'F'),
 ('Akeelah', 'F'),
 ('Abdikadir', 'M'),
 ('Arinze', 'M'),
 ('Arshaun', 'M'),
 ('Alexandro', 'M'),
 ('Ayriauna', 'F'),
 ('Aqib', 'M'),
 ('Alleya', 'F'),
 ('Aavah', 'F'),
 ('Anesti', 'Unisex'),
 ('Adalaide', 'F'),
 ('Analena', 'F'),
 ('Alaeyah', 'F'),
 ('Albena', 'F'),
 ('Aimi', 'F'),
 ('Adwaith', 'M'),
 ('Arkady', 'M'),
 ('Astyn', 'Unisex'),
 ('Adelee', 'F'),
 ('Agata', 'F'),
 ('Alegna', 'F'),
 ('Altan', 'M'),
 ('Ahnaleigh', 'F'),
 ('Algie', 'Unisex'),
 ('Ashanti', 'F'),
 ('Aislyn', 'F'),
 ('Adaleine', 'F'),
 ('Anthnoy', 'M'),
 ('Algernon', 'M'),
 ('Aeryona', 'F'),
 ('Adrinne', 'F'),
 ('Addell', 'F'),
 ('Avril', 'F'),
 ('Ahni', 'F'),
 ('Aimon', 'M'),
 ('Adolpho', 'M'),
 ('Ahuva', 'F'),
 ('Aurielle', 'F'),
 ('Aveana', 'F'),
 ('Aliyia', 'F'),
 ('Alesander', 'M'),
 ('Adnrea', 'F'),
 ('Anjae', 'F'),
 ('Alvine', 'F'),
 ('Adorah', 'F'),
 ('Adlemi', 'F'),
 ('Alesi', 'F'),
 ('Alontae', 'M'),
 ('Antonny', 'M'),
 ('Adarah', 'F'),
 ('Ayreanna', 'F'),
 ('Antyon', 'M'),
 ('Andia', 'F'),
 ('Ashla', 'F'),
 ('Aspyn', 'F'),
 ('Antwanett', 'F'),
 ('Aundreia', 'F'),
 ('Audella', 'F'),
 ('Amari', 'Unisex'),
 ('Arsha', 'Unisex'),
 ('Aricella', 'F'),
 ('Adan', 'M'),
 ('Apasra', 'F'),
 ('Alaysha', 'F'),
 ('Anderson', 'M'),
 ('Aurelius', 'M'),
 ('Aerial', 'F'),
 ('Averleigh', 'F'),
 ('Aslean', 'F'),
 ('Arniesha', 'F'),
 ('Asyana', 'F'),
 ('Annjane', 'F'),
 ('Amabella', 'F'),
 ('Austinjohn', 'M'),
 ('Arloween', 'F'),
 ('Alula', 'M'),
 ('Anemone', 'F'),
 ('Amorina', 'F'),
 ('Anureet', 'F'),
 ('Arric', 'M'),
 ('Antonne', 'M'),
 ('Alyre', 'M'),
 ('Annaise', 'F')]